site_name: RoboTwin 2.0 Offical Document
repo_url: https://github.com/RoboTwin-Platform/doc
edit_uri: edit/main/docs/
site_author: RoboTwin Team
copyright: 'Copyright &copy; 2025 RoboTwin Team'

site_url: https://RoboTwin-Platform.github.io/doc/
use_directory_urls: false
extra:
  path_prefix: /doc

nav:
  - Home:
    - index.md
    - Contributions: main/contributions.md
  - Usage:
    - usage/index.md
    - Install & Download: usage/robotwin-install.md
    - Collect Data: usage/collect-data.md
    - Domain Randomization: usage/domain-randomization.md
    - Configurations: usage/configurations.md
    - Control Robot: usage/control-robot.md
    - Policies (Env, Train & Eval):
      - Deploy Your Policy: usage/deploy-your-policy.md
      - ACT: usage/ACT.md
      - DP: usage/DP.md
      - DP3: usage/DP3.md
      - RDT: usage/RDT.md
      - Pi0: usage/Pi0.md
      - DexVLA: usage/DexVLA.md
      - TinyVLA: usage/TinyVLA.md
      - LLaVA-VLA: usage/LLaVA-VLA.md
    - Expert Code Gen (for Novel Task): usage/expert-code-gen.md
    - API Tutorial: usage/API.md
    - Dual Env (Policy and Deployment): usage/dual-env-policy-deploy.md
    - Description Gen (Object & Task): usage/description.md
    - Object Annotation: usage/object-annotation.md
    - Configuring New Embodiment: new-embodiment.md
  - Common Issue:
    - common-issue/index.md
  - 50 Bimanual Tasks:
    - tasks/index.md
    - Adjust Bottle: tasks/adjust_bottle.md
    - Beat Block Hammer: tasks/beat_block_hammer.md
    - Blocks Ranking RGB: tasks/blocks_ranking_rgb.md
    - Blocks Ranking Size: tasks/blocks_ranking_size.md
    - Click Alarmclock: tasks/click_alarmclock.md
    - Click Bell: tasks/click_bell.md
    - Dump Bin Bigbin: tasks/dump_bin_bigbin.md
    - Grab Roller: tasks/grab_roller.md
    - Handover Block: tasks/handover_block.md
    - Handover Mic: tasks/handover_mic.md
    - Hanging Mug: tasks/hanging_mug.md
    - Lift Pot: tasks/lift_pot.md
    - Move Can Pot: tasks/move_can_pot.md
    - Move Playingcard Away: tasks/move_playingcard_away.md
    - Move Stapler Pad: tasks/move_stapler_pad.md
    - Open Laptop: tasks/open_laptop.md
    - Open Microwave: tasks/open_microwave.md
    - Pick Diverse Bottles: tasks/pick_diverse_bottles.md
    - Pick Dual Bottles: tasks/pick_dual_bottles.md
    - Place A2B Left: tasks/place_a2b_left.md
    - Place A2B Right: tasks/place_a2b_right.md
    - Place Bread Basket: tasks/place_bread_basket.md
    - Place Bread Skillet: tasks/place_bread_skillet.md
    - Place Burger Fries: tasks/place_burger_fries.md
    - Place Can Basket: tasks/place_can_basket.md
    - Place Cans Plasticbox: tasks/place_cans_plasticbox.md
    - Place Container Plate: tasks/place_container_plate.md
    - Place Dual Shoes: tasks/place_dual_shoes.md
    - Place Empty Cup: tasks/place_empty_cup.md
    - Place Fan: tasks/place_fan.md
    - Place Mouse Pad: tasks/place_mouse_pad.md
    - Place Object Basket: tasks/place_object_basket.md
    - Place Object Scale: tasks/place_object_scale.md
    - Place Object Stand: tasks/place_object_stand.md
    - Place Phone Stand: tasks/place_phone_stand.md
    - Place Shoe: tasks/place_shoe.md
    - Press Stapler: tasks/press_stapler.md
    - Put Bottles Dustbin: tasks/put_bottles_dustbin.md
    - Put Object Cabinet: tasks/put_object_cabinet.md
    - Rotate QRcode: tasks/rotate_qrcode.md
    - Scan Object: tasks/scan_object.md
    - Shake Bottle Horizontally: tasks/shake_bottle_horizontally.md
    - Shake Bottle: tasks/shake_bottle.md
    - Stack Blocks Three: tasks/stack_blocks_three.md
    - Stack Blocks Two: tasks/stack_blocks_two.md
    - Stack Bowls Three: tasks/stack_bowls_three.md
    - Stack Bowls Two: tasks/stack_bowls_two.md
    - Stamp Seal: tasks/stamp_seal.md
    - Turn Switch: tasks/turn_switch.md
    - Move Pillbottle Pad: tasks/move_pillbottle_pad.md
  - Objects (RoboTwin-OD):
    - objects/index.md
    - 001_Bottle: objects/001_bottle.md
    - 002_Bowl: objects/002_bowl.md
    - 003_Plate: objects/003_plate.md
    - 004_Fluted-Block: objects/004_fluted-block.md
    - 005_French-Fries: objects/005_french-fries.md
    - 006_Hamburg: objects/006_hamburg.md
    - 007_Shoe-Box: objects/007_shoe-box.md
    - 008_Tray: objects/008_tray.md
    - 009_Kettle: objects/009_kettle.md
    - 010_Pen: objects/010_pen.md
    - 011_Dustbin: objects/011_dustbin.md
    - 012_Plant-Pot: objects/012_plant-pot.md
    - 013_Dumbbell-Rack: objects/013_dumbbell-rack.md
    - 014_Bookcase: objects/014_bookcase.md
    - 015_Laptop: objects/015_laptop.md
    - 016_Oven: objects/016_oven.md
    - 017_Calculator: objects/017_calculator.md
    - 018_Microphone: objects/018_microphone.md
    - 019_Coaster: objects/019_coaster.md
    - 020_Hammer: objects/020_hammer.md
    - 021_Cup: objects/021_cup.md
    - 022_Cup-With-Liquid: objects/022_cup-with-liquid.md
    - 023_Tissue-Box: objects/023_tissue-box.md
    - 024_Scanner: objects/024_scanner.md
    - 025_Chips-Tub: objects/025_chips-tub.md
    - 026_Pet-Collar: objects/026_pet-collar.md
    - 027_Table-Tennis: objects/027_table-tennis.md
    - 028_Roll-Paper: objects/028_roll-paper.md
    - 029_Olive-Oil: objects/029_olive-oil.md
    - 030_Drill: objects/030_drill.md
    - 031_Jam-Jar: objects/031_jam-jar.md
    - 032_Screwdriver: objects/032_screwdriver.md
    - 033_Fork: objects/033_fork.md
    - 034_Knife: objects/034_knife.md
    - 035_Apple: objects/035_apple.md
    - 036_Cabinet: objects/036_cabinet.md
    - 037_Box: objects/037_box.md
    - 038_Milk-Box: objects/038_milk-box.md
    - 039_Mug: objects/039_mug.md
    - 040_Rack: objects/040_rack.md
    - 041_Shoe: objects/041_shoe.md
    - 042_Wooden_Box: objects/042_wooden_box.md
    - 043_Book: objects/043_book.md
    - 044_Microwave: objects/044_microwave.md
    - 045_Sand-Clock: objects/045_sand-clock.md
    - 046_Alarm-Clock: objects/046_alarm-clock.md
    - 047_Mouse: objects/047_mouse.md
    - 048_Stapler: objects/048_stapler.md
    - 049_Shampoo: objects/049_shampoo.md
    - 050_Bell: objects/050_bell.md
    - 051_Candlestick: objects/051_candlestick.md
    - 052_Dumbbell: objects/052_dumbbell.md
    - 053_Teanet: objects/053_teanet.md
    - 054_Baguette: objects/054_baguette.md
    - 055_Small-Speaker: objects/055_small-speaker.md
    - 056_Switch: objects/056_switch.md
    - 057_Toycar: objects/057_toycar.md
    - 058_Markpen: objects/058_markpen.md
    - 059_Pencup: objects/059_pencup.md
    - 060_Kitchenpot: objects/060_kitchenpot.md
    - 061_Battery: objects/061_battery.md
    - 062_Plasticbox: objects/062_plasticbox.md
    - 063_Tabletrashbin: objects/063_tabletrashbin.md
    - 064_Msg: objects/064_msg.md
    - 065_Soy-Sauce: objects/065_soy-sauce.md
    - 066_Vinegar: objects/066_vinegar.md
    - 067_Steamer: objects/067_steamer.md
    - 068_Boxdrink: objects/068_boxdrink.md
    - 069_Vagetable: objects/069_vagetable.md
    - 070_Paymentsign: objects/070_paymentsign.md
    - 071_Can: objects/071_can.md
    - 072_Electronicscale: objects/072_electronicscale.md
    - 073_Rubikscube: objects/073_rubikscube.md
    - 074_Displaystand: objects/074_displaystand.md
    - 075_Bread: objects/075_bread.md
    - 076_Breadbasket: objects/076_breadbasket.md
    - 077_Phone: objects/077_phone.md
    - 078_Phonestand: objects/078_phonestand.md
    - 079_Remotecontrol: objects/079_remotecontrol.md
    - 080_Pillbottle: objects/080_pillbottle.md
    - 081_Playingcards: objects/081_playingcards.md
    - 082_Smallshovel: objects/082_smallshovel.md
    - 083_Brush: objects/083_brush.md
    - 084_Woodenmallet: objects/084_woodenmallet.md
    - 085_Gong: objects/085_gong.md
    - 086_Woodenblock: objects/086_woodenblock.md
    - 087_Waterer: objects/087_waterer.md
    - 088_Wineglass: objects/088_wineglass.md
    - 089_Globe: objects/089_globe.md
    - 090_Trophy: objects/090_trophy.md
    - 091_Kettle: objects/091_kettle.md
    - 092_Notebook: objects/092_notebook.md
    - 093_Brush-Pen: objects/093_brush-pen.md
    - 094_Rest: objects/094_rest.md
    - 095_Glue: objects/095_glue.md
    - 096_Cleaner: objects/096_cleaner.md
    - 097_Screen: objects/097_screen.md
    - 098_Speaker: objects/098_speaker.md
    - 099_Fan: objects/099_fan.md
    - 100_Seal: objects/100_seal.md
    - 101_Milk-Tea: objects/101_milk-tea.md
    - 102_Roller: objects/102_roller.md
    - 103_Fruit: objects/103_fruit.md
    - 104_Board: objects/104_board.md
    - 105_Sauce-Can: objects/105_sauce-can.md
    - 106_Skillet: objects/106_skillet.md
    - 107_Soap: objects/107_soap.md
    - 108_Block: objects/108_block.md
    - 109_Hydrating-Oil: objects/109_hydrating-oil.md
    - 110_Basket: objects/110_basket.md
    - 111_Callbell: objects/111_callbell.md
    - 112_Tea-Box: objects/112_tea-box.md
    - 113_Coffee-Box: objects/113_coffee-box.md
    - 114_Bottle: objects/114_bottle.md
    - 115_Perfume: objects/115_perfume.md
    - 116_Keyboard: objects/116_keyboard.md
    - 117_Whiteboard-Eraser: objects/117_whiteboard-eraser.md
    - 118_Tooth-Paste: objects/118_tooth-paste.md
    - 119_Mini-Chalkboard: objects/119_mini-chalkboard.md
    - 120_Plant: objects/120_plant.md
  - Community:
    - community/index.md
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
      primary: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
      primary: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.footer
    - navigation.top
    - toc.follow
    - announce.dismiss
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
  # Necessary for search to work properly
  include_search_page: false
  search_index_only: false

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search:
      lang:
        - en
        - ja
      separator: '[\s\u200b\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - git-revision-date-localized
  - add-number:
      strict_mode: False
      order: 2
  - git-authors:
      show_contribution: true
