adjust_bottle: 147
beat_block_hammer: 113
blocks_ranking_rgb: 466
blocks_ranking_size: 466
click_alarmclock: 85
click_bell: 85
dump_bin_bigbin: 265
grab_roller: 94
handover_block: 283
handover_mic: 223
hanging_mug: 340
lift_pot: 112
move_can_pot: 151
move_playingcard_away: 120
move_stapler_pad: 152
open_laptop: 258
open_microwave: 537
pick_diverse_bottles: 122
pick_dual_bottles: 127
place_a2b_left: 155
place_a2b_right: 145
place_bread_basket: 231
place_bread_skillet: 162
place_can_basket: 255
place_cans_plasticbox: 289
place_container_plate: 156
place_dual_shoes: 228
place_empty_cup: 174
place_fan: 148
place_burger_fries: 242
place_mouse_pad: 149
place_object_basket: 252
place_object_scale: 146
place_object_stand: 138
place_phone_stand: 130
move_pillbottle_pad: 147
place_shoe: 178
press_stapler: 141
put_bottles_dustbin: 637
put_object_cabinet: 274
rotate_qrcode: 155
scan_object: 170
shake_bottle: 246
shake_bottle_horizontally: 276
stack_blocks_three: 481
stack_blocks_two: 316
stack_bowls_three: 476
stack_bowls_two: 313
stamp_seal: 151
turn_switch: 95
